name: Handle Translation Request

on:
  repository_dispatch:
    types: [create_translation_task]
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  handle-translation-task:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Dynamic Environment Variables
        id: setup
        run: |
          # Generate the dynamic file path
          TODO_FILEPATH="translations/todo/todo_list_${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}-${GITHUB_RUN_ATTEMPT}.txt"
          # Export the file path to environment
          echo "TODO_FILEPATH=${TODO_FILEPATH}" >> $GITHUB_ENV
    
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set variables on workflow dispatch
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        run: |
          KEYS_MAP=$(echo '{"testKey": "testValue"}' | jq -c .)

          echo "KEYS_MAP=${KEYS_MAP}" >> $GITHUB_ENV
          echo "SOURCE_REPO=test-repo" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=test-source-branch" >> $GITHUB_ENV
          echo "TARGET_LANGUAGES=test-target-languages" >> $GITHUB_ENV

          echo "Set variables on workflow dispatch"

      - name: Set variables from client_payload
        if: github.event_name == 'repository_dispatch'
        run: | 
          # KEYS_MAP="${{ github.event.client_payload.keys }}"
          # SOURCE_REPO="${{ github.event.client_payload.repository }}"
          # SOURCE_BRANCH="${{ github.event.client_payload.branch }}"
          # TARGET_LANGUAGES="${{ github.event.client_payload.target_languages }}"

          echo "KEYS_MAP=${{ github.event.client_payload.keys }}" >> $GITHUB_ENV
          echo "SOURCE_REPO=${{ github.event.client_payload.repository }}" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV
          echo "TARGET_LANGUAGES=${{ github.event.client_payload.target_languages }}" >> $GITHUB_ENV

          echo "Set variables from client_payload"

      - name: Print inputs
        id: print-inputs
        run: |
          echo "$KEYS_MAP"
          echo "$SOURCE_REPO"
          echo "$SOURCE_BRANCH"
          echo "$TARGET_LANGUAGES"
        
      - name: Create To-Do File for Translators
        run: |
          # Create a todo directory if it doesn't exist
          mkdir -p translations/todo

          echo "File: $TODO_FILEPATH"

          # Write the keys, repository, branch, target languages, and English strings to the to-do file
          echo "Repository: $SOURCE_REPO" >> $TODO_FILEPATH
          echo "Branch: $SOURCE_BRANCH" >> $TODO_FILEPATH
          echo "Target Languages: $TARGET_LANGUAGES" >> $TODO_FILEPATH
          echo "Keys needing translation and their English values:" >> $TODO_FILEPATH

          # Iterate over the JSON map and print each key with its corresponding English value
          echo "$KEYS_MAP" | jq -r 'to_entries[] | "- \(.key): \(.value)"' >> ${TODO_FILEPATH}

          cat $TODO_FILEPATH

      - name: Commit and Push To-Do File
        run: |
          echo "TODO_FILEPATH: $TODO_FILEPATH"
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add $TODO_FILEPATH
          git commit -m "Add translation to-do list for $SOURCE_REPO ($SOURCE_BRANCH)"
          git push origin HEAD
