name: Handle Translation Request

on:
  repository_dispatch:
    types: [create_translation_task]

jobs:
  handle-translation-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.17

      - name: Create To-Do File for Translators
        run: |
          # Extract the data from the repository_dispatch payload
          KEYS="${{ github.event.client_payload.keys }}"
          SOURCE_REPO="${{ github.event.client_payload.repository }}"
          SOURCE_BRANCH="${{ github.event.client_payload.branch }}"
          TARGET_LANGUAGES="${{ github.event.client_payload.target_languages }}"
          EN_STRINGS="${{ github.event.client_payload.en_strings }}"

          # Create a todo directory if it doesn't exist
          mkdir -p translations/todo

          # Write the keys, repository, branch, target languages, and English strings to the to-do file
          echo "Repository: $SOURCE_REPO" > translations/todo/todo_list.txt
          echo "Branch: $SOURCE_BRANCH" >> translations/todo/todo_list.txt
          echo "Target Languages: $TARGET_LANGUAGES" >> translations/todo/todo_list.txt
          echo "Keys needing translation and their English values:" >> translations/todo/todo_list.txt

          IFS=',' read -ra KEYS_ARRAY <<< "$KEYS"
          IFS=',' read -ra EN_STRINGS_ARRAY <<< "$EN_STRINGS"

          for i in "${!KEYS_ARRAY[@]}"; do
            echo "- ${KEYS_ARRAY[$i]}: ${EN_STRINGS_ARRAY[$i]}" >> translations/todo/todo_list.txt
          done

      - name: Commit and Push To-Do File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add translations/todo/todo_list.txt
          git commit -m "Add translation to-do list for $SOURCE_REPO ($SOURCE_BRANCH)"
          git push origin HEAD
