name: Handle Translation Request

on:
  repository_dispatch:
    types: [create_translation_task]
  workflow_dispatch:

jobs:
  handle-translation-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.17

      - name: Set variables on workflow dispatch
        if: github.event_name == 'workflow_dispatch'
        run: |
          KEYS_MAP=$(echo '{"testKey": "testValue"}' | jq -c .)
          SOURCE_REPO="test-repo"
          SOURCE_BRANCH="test-source-branch"
          TARGET_LANGUAGES="test-target-langauges"
          echo "Set variables on workflow dispatch"

      - name: Set variables from client_payload
        if: github.event_name == 'repository_dispatch'
        run: | 
          # Extract the data from the repository_dispatch payload
          KEYS_MAP="${{ github.event.client_payload.keys }}"
          SOURCE_REPO="${{ github.event.client_payload.repository }}"
          SOURCE_BRANCH="${{ github.event.client_payload.branch }}"
          TARGET_LANGUAGES="${{ github.event.client_payload.target_languages }}"

      - name: Create To-Do File for Translators
        run: |
          # Create a todo directory if it doesn't exist
          mkdir -p translations/todo

          # Write the keys, repository, branch, target languages, and English strings to the to-do file
          echo "Repository: $SOURCE_REPO" > translations/todo/todo_list.txt
          echo "Branch: $SOURCE_BRANCH" >> translations/todo/todo_list.txt
          echo "Target Languages: $TARGET_LANGUAGES" >> translations/todo/todo_list.txt
          echo "Keys needing translation and their English values:" >> translations/todo/todo_list.txt

          # Iterate over the JSON map and print each key with its corresponding English value
          echo "$KEYS_MAP" | jq -r 'to_entries[] | "- \(.key): \(.value)"' >> translations/todo/todo_list.txt

      - name: Commit and Push To-Do File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add translations/todo/todo_list.txt
          git commit -m "Add translation to-do list for $SOURCE_REPO ($SOURCE_BRANCH)"
          git push origin HEAD
